# ImageStream for creating the image containing skopeo for signing. 
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: signer
  name: signer
  namespace: kabanero
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: ""
