# ImageStream for creating the scanner image
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: scanner
  name: scanner
  namespace: kabanero
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: docker-registry.default.svc:5000/kabanero/scanner